spring.application.name=salonBelleza

# PUERTO
server.port=47

# MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/salon_belleza?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=PalMldz11-
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# THYMELEAF
spring.thymeleaf.cache=false
